# Use the official MongoDB image
FROM mongo:latest

# Set the container's working directory to /data/db which is the default mount point for MongoDB data
WORKDIR /data/db

# Expose the default MongoDB port
EXPOSE 27017

# Run mongod with the default command
CMD ["mongod"]